version: '3'

services:
  vue-docker-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:8080"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development

  git-container:
    image: alpine/git
    volumes:
      - ./:/git-repo

    command: ["pull"]

