version: "3.4"
services:
  vue-app:
    container_name: vue-app
    image: node:lts
    working_dir: /var/www/html/app/
    ports:
      - "8000:8000"  # This line maps the container's port 8000 to the host's port 8000
    volumes:
      - ./vue-app:/var/www/html/app
    command: ["npm", "run", "dev"]
